#! /bin/bash
#
# This is a maintainer post-removal script for an ExaGear guest image package.
#
# Copyright (c) 2016 "Elbrus Technologies" LLC. All rights reserved.
#
# This script comes with NO warranty, not even for MERCHANTABILITY or
# FITNESS FOR A PARTICULAR PURPOSE.
#

case "$1" in
    remove|purge)
        rm -rf $(grep -l __WRAPPED_FOR_EXAGEAR_GUEST_UBUNTU_1604 /etc/init/*)\
               /opt/exagear/images/ubuntu-1604 \
            >/dev/null 2>&1
        ;;
esac

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d exagear-guest-ubuntu-1604 remove >/dev/null
fi
# End automatically added section


exit 0
